export type SoftwareCategory =
  | "杀软/安全防护"
  | "办公软件"
  | "终端/远控"
  | "其他常见程序";

export interface SoftwareSignature {
  id: string;
  category: SoftwareCategory;
  displayName: string;
  processes: string[];
  aliases?: string[];
  description?: string;
  source?: "curated" | "legacy";
}

const lower = (value: string) => value.toLowerCase();

export const SOFTWARE_SIGNATURES: SoftwareSignature[] = [
  {
    id: "defender",
    category: "杀软/安全防护",
    displayName: "Windows Defender (微软)",
    processes: [
      "MsMpEng.exe",
      "NisSrv.exe",
      "SecurityHealthService.exe",
      "SecurityHealthSystray.exe",
    ],
    description: "Windows 10/11 自带安全中心组件",
  },
  {
    id: "360safe",
    category: "杀软/安全防护",
    displayName: "360 安全卫士",
    processes: [
      "360Tray.exe",
      "360Safe.exe",
      "360sd.exe",
      "360rp.exe",
      "ZhuDongFangYu.exe",
    ],
    description: "常见国产主机安全产品",
  },
  {
    id: "360killer",
    category: "杀软/安全防护",
    displayName: "360 杀毒",
    processes: ["360sd.exe", "360safebox.exe", "QHSafeTray.exe"],
  },
  {
    id: "qqpcmgr",
    category: "杀软/安全防护",
    displayName: "腾讯电脑管家",
    processes: ["QQPCTray.exe", "QQPCRtp.exe", "QQPCNetFlow.exe"],
  },
  {
    id: "kaspersky",
    category: "杀软/安全防护",
    displayName: "卡巴斯基",
    processes: ["avp.exe", "kavsvc.exe", "avpui.exe"],
  },
  {
    id: "eset",
    category: "杀软/安全防护",
    displayName: "ESET NOD32 / Endpoint Security",
    processes: ["egui.exe", "ekrn.exe"],
  },
  {
    id: "symantec",
    category: "杀软/安全防护",
    displayName: "Symantec / SEP",
    processes: ["ccSvcHst.exe", "Smc.exe", "SmcGui.exe"],
  },
  {
    id: "trendmicro",
    category: "杀软/安全防护",
    displayName: "趋势科技 (Trend Micro)",
    processes: ["TmPfw.exe", "NTRtScan.exe", "TmListen.exe"],
  },
  {
    id: "mcafee",
    category: "杀软/安全防护",
    displayName: "McAfee",
    processes: ["mcshield.exe", "masvc.exe", "mfemms.exe"],
  },
  {
    id: "bitdefender",
    category: "杀软/安全防护",
    displayName: "Bitdefender",
    processes: ["bdservicehost.exe", "bdagent.exe"],
  },
  {
    id: "360es",
    category: "杀软/安全防护",
    displayName: "360 企业安全",
    processes: ["qpsafesvc.exe", "qpsafetray.exe"],
  },
  {
    id: "rising",
    category: "杀软/安全防护",
    displayName: "瑞星杀毒",
    processes: ["ravmon.exe", "rav.exe"],
  },
  {
    id: "huorong",
    category: "杀软/安全防护",
    displayName: "火绒安全",
    processes: [
      "HipsTray.exe",
      "HipsMain.exe",
      "HrCfgLoader.exe",
      "Wsctrl.exe",
    ],
  },
  {
    id: "sangfor",
    category: "杀软/安全防护",
    displayName: "深信服 EDR/终端防护",
    processes: ["SangforUM.exe", "SangforSvc.exe"],
  },
  {
    id: "tencent-apm",
    category: "杀软/安全防护",
    displayName: "腾讯 TPA / EDR",
    processes: ["TPAutoConnSvc.exe", "TPAutoDetect.exe"],
  },
  {
    id: "office",
    category: "办公软件",
    displayName: "Microsoft Office (Word/Excel/PPT)",
    processes: ["WINWORD.EXE", "EXCEL.EXE", "POWERPNT.EXE", "OUTLOOK.EXE"],
  },
  {
    id: "office-onedrive",
    category: "办公软件",
    displayName: "Microsoft Teams / OneDrive",
    processes: ["Teams.exe", "OneDrive.exe"],
  },
  {
    id: "wps",
    category: "办公软件",
    displayName: "金山 WPS 套件",
    processes: ["wps.exe", "wpp.exe", "et.exe"],
  },
  {
    id: "pdf",
    category: "办公软件",
    displayName: "PDF 阅读器",
    processes: ["AcroRd32.exe", "Acrobat.exe", "FoxitPDFReader.exe"],
  },
  {
    id: "shell",
    category: "终端/远控",
    displayName: "Windows 原生命令终端",
    processes: ["cmd.exe", "powershell.exe", "pwsh.exe", "conhost.exe"],
    description: "包含 CMD、PowerShell、pwsh 等终端进程",
  },
  {
    id: "windows-terminal",
    category: "终端/远控",
    displayName: "Windows Terminal",
    processes: ["wt.exe", "WindowsTerminal.exe"],
  },
  {
    id: "wsl",
    category: "终端/远控",
    displayName: "WSL / Bash",
    processes: ["bash.exe", "wsl.exe"],
  },
  {
    id: "mstsc",
    category: "终端/远控",
    displayName: "远程桌面 (mstsc)",
    processes: ["mstsc.exe"],
  },
  {
    id: "putty",
    category: "终端/远控",
    displayName: "PuTTY / KiTTY",
    processes: ["putty.exe", "kitty.exe"],
  },
  {
    id: "xshell",
    category: "终端/远控",
    displayName: "Xshell",
    processes: ["Xshell.exe", "Xagent.exe", "Xftp.exe"],
  },
  {
    id: "securecrt",
    category: "终端/远控",
    displayName: "SecureCRT",
    processes: ["SecureCRT.exe"],
  },
  {
    id: "mobaxterm",
    category: "终端/远控",
    displayName: "MobaXterm",
    processes: ["MobaXterm.exe"],
  },
  {
    id: "navicat",
    category: "其他常见程序",
    displayName: "Navicat 数据库客户端",
    processes: ["navicat.exe"],
  },
  {
    id: "dbeaver",
    category: "其他常见程序",
    displayName: "DBeaver",
    processes: ["dbeaver.exe"],
  },
  {
    id: "vscode",
    category: "其他常见程序",
    displayName: "VS Code",
    processes: ["Code.exe"],
  },
  {
    id: "python",
    category: "其他常见程序",
    displayName: "Python 解释器",
    processes: ["python.exe", "pythonw.exe"],
  },
];

SOFTWARE_SIGNATURES.forEach((signature) => {
  if (!signature.source) {
    signature.source = "curated";
  }
});

export const PROCESS_LOOKUP = new Map<string, SoftwareSignature>();
SOFTWARE_SIGNATURES.forEach((signature) => {
  signature.processes.forEach((proc) =>
    PROCESS_LOOKUP.set(lower(proc), signature),
  );
  signature.aliases?.forEach((alias) =>
    PROCESS_LOOKUP.set(lower(alias), signature),
  );
});

const LEGACY_AV_LIST: Record<string, string> = {
  "360tray.exe": "360安全卫士-实时保护",
  "360safe.exe": "360安全卫士-主程序",
  "ZhuDongFangYu.exe": "360安全卫士-主动防御",
  "360sd.exe": "360杀毒",
  "a2guard.exe": "a-squared杀毒",
  "ad-watch.exe": "Lavasoft杀毒",
  "cleaner8.exe": "The Cleaner杀毒",
  "vba32lder.exe": "vb32杀毒",
  "MongoosaGUI.exe": "Mongoosa杀毒",
  "CorantiControlCenter32.exe": "Coranti2012杀毒",
  "F-PROT.exe": "F-Prot AntiVirus",
  "CMCTrayIcon.exe": "CMC杀毒",
  "K7TSecurity.exe": "K7杀毒",
  "UnThreat.exe": "UnThreat杀毒",
  "CKSoftShiedAntivirus4.exe": "Shield Antivirus杀毒",
  "AVWatchService.exe": "VIRUSfighter杀毒",
  "ArcaTasksService.exe": "ArcaVir杀毒",
  "iptray.exe": "Immunet杀毒",
  "PSafeSysTray.exe": "PSafe杀毒",
  "nspupsvc.exe": "nProtect杀毒",
  "SpywareTerminatorShield.exe": "SpywareTerminator反间谍软件",
  "BKavService.exe": "Bkav杀毒",
  "MsMpEng.exe": "Windows Defender",
  "SBAMSvc.exe": "VIPRE",
  "ccSvcHst.exe": "Norton杀毒",
  "f-secure.exe": "冰岛",
  "avp.exe": "Kaspersky",
  "KvMonXP.exe": "江民杀毒",
  "RavMonD.exe": "瑞星杀毒",
  "Mcshield.exe": "McAfee",
  "Tbmon.exe": "McAfee",
  "Frameworkservice.exe": "McAfee",
  "egui.exe": "ESET NOD32",
  "ekrn.exe": "ESET NOD32",
  "eguiProxy.exe": "ESET NOD32",
  "kxetray.exe": "金山毒霸",
  "knsdtray.exe": "可牛杀毒",
  "TMBMSRV.exe": "趋势杀毒",
  "avcenter.exe": "Avira(小红伞)",
  "avguard.exe": "Avira(小红伞)",
  "avgnt.exe": "Avira(小红伞)",
  "sched.exe": "Avira(小红伞)",
  "ashDisp.exe": "Avast网络安全",
  "rtvscan.exe": "诺顿杀毒",
  "ccapp.exe": "SymantecNorton",
  "NPFMntor.exe": "Norton杀毒软件",
  "ccSetMgr.exe": "赛门铁克",
  "ccRegVfy.exe": "Norton杀毒软件",
  "ksafe.exe": "金山卫士",
  "QQPCRTP.exe": "QQ电脑管家",
  "avgwdsvc.exe": "AVG杀毒",
  "QUHLPSVC.exe": "QUICK HEAL杀毒",
  "mssecess.exe": "微软杀毒",
  "SavProgress.exe": "Sophos杀毒",
  "SophosUI.exe": "Sophos杀毒",
  "SophosFS.exe": "Sophos杀毒",
  "SophosHealth.exe": "Sophos杀毒",
  "SophosSafestore64.exe": "Sophos杀毒",
  "SophosCleanM.exe": "Sophos杀毒",
  "fsavgui.exe": "F-Secure杀毒",
  "vsserv.exe": "比特梵德",
  "remupd.exe": "熊猫卫士",
  "FortiTray.exe": "飞塔",
  "safedog.exe": "安全狗",
  "parmor.exe": "木马克星",
  "Iparmor.exe.exe": "木马克星",
  "beikesan.exe": "贝壳云安全",
  "KSWebShield.exe": "金山网盾",
  "TrojanHunter.exe": "木马猎手",
  "GG.exe": "巨盾网游安全盾",
  "adam.exe": "绿鹰安全精灵",
  "AST.exe": "超级巡警",
  "ananwidget.exe": "墨者安全专家",
  "AVK.exe": "AntiVirusKit",
  "avg.exe": "AVG Anti-Virus",
  "spidernt.exe": "Dr.web",
  "avgaurd.exe": "Avira Antivir",
  "vsmon.exe": "Zone Alarm",
  "cpf.exe": "Comodo",
  "outpost.exe": "Outpost Firewall",
  "rfwmain.exe": "瑞星防火墙",
  "kpfwtray.exe": "金山网镖",
  "FYFireWall.exe": "风云防火墙",
  "MPMon.exe": "微点主动防御",
  "pfw.exe": "天网防火墙",
  "BaiduSdSvc.exe": "百度杀毒-服务进程",
  "BaiduSdTray.exe": "百度杀毒-托盘进程",
  "BaiduSd.exe": "百度杀毒-主程序",
  "SafeDogGuardCenter.exe": "安全狗",
  "safedogupdatecenter.exe": "安全狗",
  "safedogguardcenter.exe": "安全狗",
  "SafeDogSiteIIS.exe": "安全狗",
  "SafeDogTray.exe": "安全狗",
  "SafeDogServerUI.exe": "安全狗",
  "D_Safe_Manage.exe": "D盾",
  "d_manage.exe": "D盾",
  "yunsuo_agent_service.exe": "云锁",
  "yunsuo_agent_daemon.exe": "云锁",
  "HwsPanel.exe": "护卫神",
  "hws_ui.exe": "护卫神",
  "hws.exe": "护卫神",
  "hwsd.exe": "护卫神",
  "HipsTray.exe": "火绒",
  "HipsDaemon.exe": "火绒",
  "wsctrl.exe": "火绒",
  "usysdiag.exe": "火绒",
  "SPHINX.exe": "SPHINX防火墙",
  "bddownloader.exe": "百度卫士",
  "baiduansvx.exe": "百度卫士-主进程",
  "AvastUI.exe": "Avast!5主程序",
  "emet_agent.exe": "EMET",
  "emet_service.exe": "EMET",
  "firesvc.exe": "McAfee",
  "firetray.exe": "McAfee",
  "hipsvc.exe": "McAfee",
  "mfevtps.exe": "McAfee",
  "mcafeefire.exe": "McAfee",
  "scan32.exe": "McAfee",
  "shstat.exe": "McAfee",
  "vstskmgr.exe": "McAfee",
  "engineserver.exe": "McAfee",
  "mfeann.exe": "McAfee",
  "mcscript.exe": "McAfee",
  "updaterui.exe": "McAfee",
  "udaterui.exe": "McAfee",
  "naprdmgr.exe": "McAfee",
  "cleanup.exe": "McAfee",
  "cmdagent.exe": "McAfee",
  "frminst.exe": "McAfee",
  "mcscript_inuse.exe": "McAfee",
  "mctray.exe": "McAfee",
  "_avp32.exe": "卡巴斯基",
  "_avpcc.exe": "卡巴斯基",
  "_avpm.exe": "卡巴斯基",
  "aAvgApi.exe": "AVG",
  "ackwin32.exe": "已知杀软进程,名称暂未收录",
  "alertsvc.exe": "Norton AntiVirus",
  "alogserv.exe": "McAfee VirusScan",
  "anti-trojan.exe": "Anti-Trojan Elite",
  "arr.exe": "Application Request Route",
  "atguard.exe": "AntiVir",
  "atupdater.exe": "已知杀软进程,名称暂未收录",
  "atwatch.exe": "Mustek",
  "au.exe": "NSIS",
  "aupdate.exe": "Symantec",
  "auto-protect.nav80try.exe": "已知杀软进程,名称暂未收录",
  "autodown.exe": "AntiVirus AutoUpdater",
  "avconsol.exe": "McAfee",
  "avgcc32.exe": "AVG",
  "avgctrl.exe": "AVG",
  "avgemc.exe": "AVG",
  "avgrsx.exe": "AVG",
  "avgserv.exe": "AVG",
  "avgserv9.exe": "AVG",
  "avgw.exe": "AVG",
  "avkpop.exe": "G DATA SOFTWARE AG",
  "avkserv.exe": "G DATA SOFTWARE AG",
  "avkservice.exe": "G DATA SOFTWARE AG",
  "avkwctl9.exe": "G DATA SOFTWARE AG",
  "avltmain.exe": "Panda Software Aplication",
  "avnt.exe": "H+BEDV Datentechnik GmbH",
  "avp32.exe": "Kaspersky Anti-Virus",
  "avpcc.exe": " Kaspersky AntiVirus",
  "avpdos32.exe": " Kaspersky AntiVirus",
  "avpm.exe": " Kaspersky AntiVirus",
  "avptc32.exe": " Kaspersky AntiVirus",
  "avpupd.exe": " Kaspersky AntiVirus",
  "avsynmgr.exe": "McAfee",
  "avwin.exe": " H+BEDV",
  "bargains.exe": "Exact Advertising SpyWare",
  "beagle.exe": "Avast",
  "blackd.exe": "BlackICE",
  "blackice.exe": "BlackICE",
  "blink.exe": "micromedia",
  "blss.exe": "CBlaster",
  "bootwarn.exe": "Symantec",
  "bpc.exe": "Grokster",
  "brasil.exe": "Exact Advertising",
  "ccevtmgr.exe": "Norton Internet Security",
  "cdp.exe": "CyberLink Corp.",
  "cfd.exe": "Motive Communications",
  "cfgwiz.exe": " Norton AntiVirus",
  "claw95.exe": "已知杀软进程,名称暂未收录",
  "claw95cf.exe": "已知杀软进程,名称暂未收录",
  "clean.exe": "windows流氓软件清理大师",
  "cleaner.exe": "windows流氓软件清理大师",
  "cleaner3.exe": "windows流氓软件清理大师",
  "cleanpc.exe": "windows流氓软件清理大师",
  "cpd.exe": "McAfee",
  "ctrl.exe": "已知杀软进程,名称暂未收录",
  "cv.exe": "已知杀软进程,名称暂未收录",
  "defalert.exe": "Symantec",
  "defscangui.exe": "Symantec",
  "defwatch.exe": "Norton Antivirus",
  "doors.exe": "已知杀软进程,名称暂未收录",
  "dpf.exe": "已知杀软进程,名称暂未收录",
  "dpps2.exe": "PanicWare",
  "dssagent.exe": "Broderbund",
  "ecengine.exe": "已知杀软进程,名称暂未收录",
  "emsw.exe": "Alset Inc",
  "ent.exe": "已知杀软进程,名称暂未收录",
  "espwatch.exe": "已知杀软进程,名称暂未收录",
  "ethereal.exe": "RationalClearCase",
  "exe.avxw.exe": "已知杀软进程,名称暂未收录",
  "expert.exe": "已知杀软进程,名称暂未收录",
  "f-prot95.exe": "已知杀软进程,名称暂未收录",
  "fameh32.exe": "F-Secure",
  "fast.exe": " FastUsr",
  "fch32.exe": "F-Secure",
  "fih32.exe": "F-Secure",
  "findviru.exe": "F-Secure",
  "firewall.exe": "AshampooSoftware",
  "fnrb32.exe": "F-Secure",
  "fp-win.exe": " F-Prot Antivirus OnDemand",
  "fsaa.exe": "F-Secure",
  "fsav.exe": "F-Secure",
  "fsav32.exe": "F-Secure",
  "fsav530stbyb.exe": "F-Secure",
  "fsav530wtbyb.exe": "F-Secure",
  "fsav95.exe": "F-Secure",
  "fsgk32.exe": "F-Secure",
  "fsm32.exe": "F-Secure",
  "fsma32.exe": "F-Secure",
  "fsmb32.exe": "F-Secure",
  "gbmenu.exe": "已知杀软进程,名称暂未收录",
  "guard.exe": "ewido",
  "guarddog.exe": "ewido",
  "htlog.exe": "已知杀软进程,名称暂未收录",
  "htpatch.exe": "Silicon Integrated Systems Corporation",
  "hwpe.exe": "已知杀软进程,名称暂未收录",
  "iamapp.exe": "Symantec",
  "iamserv.exe": "Symantec",
  "iamstats.exe": "Symantec",
  "iedriver.exe": " Urlblaze.com",
  "iface.exe": "Panda Antivirus Module",
  "infus.exe": "Infus Dialer",
  "infwin.exe": "Msviewparasite",
  "intdel.exe": "Inet Delivery",
  "intren.exe": "已知杀软进程,名称暂未收录",
  "jammer.exe": "已知杀软进程,名称暂未收录",
  "kavpf.exe": "Kapersky",
  "kazza.exe": "Kapersky",
  "keenvalue.exe": "EUNIVERSE INC",
  "launcher.exe": "Intercort Systems",
  "ldpro.exe": "已知杀软进程,名称暂未收录",
  "ldscan.exe": "Windows Trojans Inspector",
  "localnet.exe": "已知杀软进程,名称暂未收录",
  "luall.exe": "Symantec",
  "luau.exe": "Symantec",
  "lucomserver.exe": "Norton",
  "mcagent.exe": "McAfee",
  "mcmnhdlr.exe": "McAfee",
  "mctool.exe": "McAfee",
  "mcupdate.exe": "McAfee",
  "mcvsrte.exe": "McAfee",
  "mcvsshld.exe": "McAfee",
  "mfin32.exe": "MyFreeInternetUpdate",
  "mfw2en.exe": "MyFreeInternetUpdate",
  "mfweng3.02d30.exe": "MyFreeInternetUpdate",
  "mgavrtcl.exe": "McAfee",
  "mgavrte.exe": "McAfee",
  "mghtml.exe": "McAfee",
  "mgui.exe": "BullGuard",
  "minilog.exe": "Zone Labs Inc",
  "mmod.exe": "EzulaInc",
  "mostat.exe": "WurldMediaInc",
  "mpfagent.exe": "McAfee",
  "mpfservice.exe": "McAfee",
  "mpftray.exe": "McAfee",
  "mscache.exe": "Integrated Search Technologies Spyware",
  "mscman.exe": "OdysseusMarketingInc",
  "msmgt.exe": "Total Velocity Spyware",
  "msvxd.exe": "W32/Datom-A",
  "mwatch.exe": "已知杀软进程,名称暂未收录",
  "nav.exe": "Reuters Limited",
  "navapsvc.exe": "Norton AntiVirus",
  "navapw32.exe": "Norton AntiVirus",
  "navw32.exe": "Norton Antivirus",
  "ndd32.exe": "诺顿磁盘医生",
  "neowatchlog.exe": "已知杀软进程,名称暂未收录",
  "netutils.exe": "已知杀软进程,名称暂未收录",
  "nisserv.exe": "Norton",
  "nisum.exe": "Norton",
  "nmain.exe": "Norton",
  "nod32.exe": "ESET Smart Security",
  "norton_internet_secu_3.0_407.exe": "已知杀软进程,名称暂未收录",
  "notstart.exe": "已知杀软进程,名称暂未收录",
  "nprotect.exe": "Symantec",
  "npscheck.exe": "Norton",
  "npssvc.exe": "Norton",
  "ntrtscan.exe": "趋势反病毒应用程序",
  "nui.exe": "已知杀软进程,名称暂未收录",
  "otfix.exe": "已知杀软进程,名称暂未收录",
  "outpostinstall.exe": "Outpost",
  "patch.exe": "趋势科技",
  "pavw.exe": "已知杀软进程,名称暂未收录",
  "pcscan.exe": "趋势科技",
  "pdsetup.exe": "已知杀软进程,名称暂未收录",
  "persfw.exe": "Tiny Personal Firewall",
  "pgmonitr.exe": "PromulGate SpyWare",
  "pingscan.exe": "已知杀软进程,名称暂未收录",
  "platin.exe": "已知杀软进程,名称暂未收录",
  "pop3trap.exe": "PC-cillin",
  "poproxy.exe": "NortonAntiVirus",
  "popscan.exe": "已知杀软进程,名称暂未收录",
  "powerscan.exe": "Integrated Search Technologies",
  "ppinupdt.exe": "已知杀软进程,名称暂未收录",
  "pptbc.exe": "已知杀软进程,名称暂未收录",
  "ppvstop.exe": "已知杀软进程,名称暂未收录",
  "prizesurfer.exe": "Prizesurfer",
  "prmt.exe": "OpiStat",
  "prmvr.exe": "Adtomi",
  "processmonitor.exe": "Sysinternals",
  "proport.exe": "已知杀软进程,名称暂未收录",
  "protectx.exe": "ProtectX",
  "pspf.exe": "已知杀软进程,名称暂未收录",
  "purge.exe": "已知杀软进程,名称暂未收录",
  "qconsole.exe": "Norton AntiVirus Quarantine Console",
  "qserver.exe": "Norton Internet Security",
  "rapapp.exe": "BlackICE",
  "rb32.exe": "RapidBlaster",
  "rcsync.exe": "PrizeSurfer",
  "realmon.exe": "Realmon ",
  "rescue.exe": "已知杀软进程,名称暂未收录",
  "rescue32.exe": "卡巴斯基互联网安全套装",
  "rshell.exe": "已知杀软进程,名称暂未收录",
  "rtvscn95.exe": "Real-time virus scanner ",
  "rulaunch.exe": "McAfee User Interface",
  "run32dll.exe": "PAL PC Spy",
  "safeweb.exe": "PSafe Tecnologia",
  "sbserv.exe": "Norton Antivirus",
  "scrscan.exe": "360杀毒",
  "sfc.exe": "System file checker",
  "sh.exe": "MKS Toolkit for Win3",
  "showbehind.exe": "MicroSmarts Enterprise Component ",
  "soap.exe": "System Soap Pro",
  "sofi.exe": "已知杀软进程,名称暂未收录",
  "sperm.exe": "已知杀软进程,名称暂未收录",
  "supporter5.exe": "eScorcher反病毒",
  "symproxysvc.exe": "Symantec",
  "symtray.exe": "Symantec",
  "tbscan.exe": "ThunderBYTE",
  "tc.exe": "TimeCalende",
  "titanin.exe": "TitanHide",
  "tvmd.exe": "Total Velocity",
  "tvtmd.exe": " Total Velocity",
  "vettray.exe": "eTrust",
  "vir-help.exe": "已知杀软进程,名称暂未收录",
  "vnpc3000.exe": "已知杀软进程,名称暂未收录",
  "vpc32.exe": "Symantec",
  "vpc42.exe": "Symantec",
  "vshwin32.exe": "McAfee",
  "vsmain.exe": "McAfee",
  "vsstat.exe": "McAfee",
  "wfindv32.exe": "已知杀软进程,名称暂未收录",
  "zapro.exe": "Zone Alarm",
  "zonealarm.exe": "Zone Alarm",
  "AVPM.exe": "Kaspersky",
  "A2CMD.exe": "Emsisoft Anti-Malware",
  "A2SERVICE.exe": "a-squared free",
  "A2FREE.exe": "a-squared Free",
  "ADVCHK.exe": "Norton AntiVirus",
  "AGB.exe": "安天防线",
  "AHPROCMONSERVER.exe": "安天防线",
  "AIRDEFENSE.exe": "AirDefense",
  "ALERTSVC.exe": "Norton AntiVirus",
  "AVIRA.exe": "小红伞杀毒",
  "AMON.exe": "Tiny Personal Firewall",
  "AVZ.exe": "AVZ",
  "ANTIVIR.exe": "已知杀软进程,名称暂未收录",
  "APVXDWIN.exe": "熊猫卫士",
  "ASHMAISV.exe": "Alwil",
  "ASHSERV.exe": "Avast Anti-virus",
  "ASHSIMPL.exe": "AVAST!VirusCleaner",
  "ASHWEBSV.exe": "Avast",
  "ASWUPDSV.exe": "Avast",
  "ASWSCAN.exe": "Avast",
  "AVCIMAN.exe": "熊猫卫士",
  "AVCONSOL.exe": "McAfee",
  "AVENGINE.exe": "熊猫卫士",
  "AVESVC.exe": "Avira AntiVir Security Service",
  "AVEVL32.exe": "已知杀软进程,名称暂未收录",
  "AVGAM.exe": "AVG",
  "AVGCC.exe": "AVG",
  "AVGCHSVX.exe": "AVG",
  AVGCSRVX: "AVG",
  "AVGNSX.exe": "AVG",
  "AVGCC32.exe": "AVG",
  "AVGCTRL.exe": "AVG",
  "AVGEMC.exe": "AVG",
  "AVGFWSRV.exe": "AVG",
  "AVGNTMGR.exe": "AVG",
  "AVGSERV.exe": "AVG",
  "AVGTRAY.exe": "AVG",
  "AVGUPSVC.exe": "AVG",
  "AVINITNT.exe": "Command AntiVirus for NT Server",
  "AVPCC.exe": "Kaspersky",
  "AVSERVER.exe": "Kerio MailServer",
  "AVSCHED32.exe": "H+BEDV",
  "AVSYNMGR.exe": "McAfee",
  "AVWUPSRV.exe": "H+BEDV",
  "BDSWITCH.exe": "BitDefender Module",
  "BLACKD.exe": "BlackICE",
  "CCEVTMGR.exe": "Symantec",
  "CFP.exe": "COMODO",
  "CLAMWIN.exe": "ClamWin Portable",
  "CUREIT.exe": "DrWeb CureIT",
  "DEFWATCH.exe": "Norton Antivirus",
  "DRWADINS.exe": "Dr.Web",
  "DRWEB.exe": "Dr.Web",
  "DEFENDERDAEMON.exe": "ShadowDefender",
  "EWIDOCTRL.exe": "Ewido Security Suite",
  "EZANTIVIRUSREGISTRATIONCHECK.exe": "e-Trust Antivirus",
  "FIREWALL.exe": "AshampooSoftware",
  "FPROTTRAY.exe": "F-PROT Antivirus",
  "FPWIN.exe": "Verizon",
  "FRESHCLAM.exe": "ClamAV",
  "FSAV32.exe": "F-Secure",
  "FSBWSYS.exe": "F-secure",
  "FSDFWD.exe": "F-Secure",
  "FSGK32.exe": "F-Secure",
  "FSGK32ST.exe": "F-Secure",
  "FSMA32.exe": "F-Secure",
  "FSMB32.exe": "F-Secure",
  "FSSM32.exe": "F-Secure",
  "GUARDGUI.exe": "网游保镖",
  "GUARDNT.exe": "IKARUS",
  "IAMAPP.exe": "Symantec",
  "INOCIT.exe": "eTrust",
  "INORPC.exe": "eTrust",
  "INORT.exe": "eTrust",
  "INOTASK.exe": "eTrust",
  "INOUPTNG.exe": "eTrust",
  "ISAFE.exe": "eTrust",
  "KAV.exe": "Kaspersky",
  "KAVMM.exe": "Kaspersky",
  "KAVPF.exe": "Kaspersky",
  "KAVPFW.exe": "Kaspersky",
  "KAVSTART.exe": "Kaspersky",
  "KAVSVC.exe": "Kaspersky",
  "KAVSVCUI.exe": "Kaspersky",
  "KMAILMON.exe": "金山毒霸",
  "MCAGENT.exe": "McAfee",
  "MCMNHDLR.exe": "McAfee",
  "MCREGWIZ.exe": "McAfee",
  "MCUPDATE.exe": "McAfee",
  "MCVSSHLD.exe": "McAfee",
  "MINILOG.exe": "Zone Alarm",
  "MYAGTSVC.exe": "McAfee",
  "MYAGTTRY.exe": "McAfee",
  "NAVAPSVC.exe": "Norton",
  "NAVAPW32.exe": "Norton",
  "NAVLU32.exe": "Norton",
  "NAVW32.exe": "Norton Antivirus",
  "NEOWATCHLOG.exe": "NeoWatch",
  "NEOWATCHTRAY.exe": "NeoWatch",
  "NISSERV.exe": "Norton",
  "NISUM.exe": "Norton",
  "NMAIN.exe": "Norton",
  "NOD32.exe": "ESET NOD32",
  "NPFMSG.exe": "Norman个人防火墙",
  "NPROTECT.exe": "Symantec",
  "NSMDTR.exe": "Norton",
  "NTRTSCAN.exe": "趋势科技",
  "OFCPFWSVC.exe": "OfficeScanNT",
  "ONLINENT.exe": "已知杀软进程,名称暂未收录",
  "OP_MON.exe": " OutpostFirewall",
  "PAVFIRES.exe": "熊猫卫士",
  "PAVFNSVR.exe": "熊猫卫士",
  "PAVKRE.exe": "熊猫卫士",
  "PAVPROT.exe": "熊猫卫士",
  "PAVPROXY.exe": "熊猫卫士",
  "PAVPRSRV.exe": "熊猫卫士",
  "PAVSRV51.exe": "熊猫卫士",
  "PAVSS.exe": "熊猫卫士",
  "PCCGUIDE.exe": "PC-cillin",
  "PCCIOMON.exe": "PC-cillin",
  "PCCNTMON.exe": "PC-cillin",
  "PCCPFW.exe": "趋势科技",
  "PCCTLCOM.exe": "趋势科技",
  "PCTAV.exe": "PC Tools AntiVirus",
  "PERSFW.exe": "Tiny Personal Firewall",
  "PERVAC.exe": "已知杀软进程,名称暂未收录",
  "PESTPATROL.exe": "Ikarus",
  "PREVSRV.exe": "熊猫卫士",
  "RTVSCN95.exe": "Real-time Virus Scanner",
  "SAVADMINSERVICE.exe": "SAV",
  "SAVMAIN.exe": "SAV",
  "SAVSCAN.exe": "SAV",
  "SDHELP.exe": "Spyware Doctor",
  "SHSTAT.exe": "McAfee",
  "SPBBCSVC.exe": "Symantec",
  "SPIDERCPL.exe": "Dr.Web",
  "SPIDERML.exe": "Dr.Web",
  "SPIDERUI.exe": "Dr.Web",
  "SPYBOTSD.exe": "Spybot ",
  "SWAGENT.exe": "SonicWALL",
  "SWDOCTOR.exe": "SonicWALL",
  "SWNETSUP.exe": "Sophos",
  "SYMLCSVC.exe": "Symantec",
  "SYMPROXYSVC.exe": "Symantec",
  "SYMSPORT.exe": "Sysmantec",
  "SYMWSC.exe": "Sysmantec",
  "SYNMGR.exe": "Sysmantec",
  "TMLISTEN.exe": "趋势科技",
  "TMNTSRV.exe": "趋势科技",
  "TMPROXY.exe": "趋势科技",
  "TNBUTIL.exe": "Anti-Virus",
  "VBA32ECM.exe": "已知杀软进程,名称暂未收录",
  "VBA32IFS.exe": "已知杀软进程,名称暂未收录",
  "VBA32PP3.exe": "已知杀软进程,名称暂未收录",
  "VCRMON.exe": "VirusChaser",
  "VRMONNT.exe": "HAURI",
  "VRMONSVC.exe": "HAURI",
  "VSHWIN32.exe": "McAfee",
  "VSSTAT.exe": "McAfee",
  "XCOMMSVR.exe": "BitDefender",
  "ZONEALARM.exe": "Zone Alarm",
  "360rp.exe": "360杀毒",
  "afwServ.exe": " Avast Antivirus ",
  "safeboxTray.exe": "360杀毒",
  "360safebox.exe": "360杀毒",
  "QQPCTray.exe": "QQ电脑管家",
  "KSafeTray.exe": "金山毒霸",
  "KSafeSvc.exe": "金山毒霸",
  "KWatch.exe": "金山毒霸",
  "gov_defence_service.exe": "云锁",
  "gov_defence_daemon.exe": "云锁",
  "smartscreen.exe": "Windows Defender",
  "macompatsvc.exe": "McAfee",
  "mcamnsvc.exe ": "McAfee",
  "masvc.exe": "McAfee",
  "mfemms.exe": "McAfee",
  "mctary.exe": "McAfee",
  "mcshield.exe": "McAfee",
  "mfewc.exe": "McAfee",
  "mfewch.exe": "McAfee",
  "mfefw.exe": "McAfee",
  "mfefire.exe": "McAfee",
  "mfetp.exe": "McAfee",
  "mfecanary.exe": "McAfee",
  "mfeconsole.exe": "McAfee",
  "mfeesp.exe": "McAfee",
  "fcag.exe": "McAfee",
  "fcags.exe": "McAfee",
  "fcagswd.exe": "McAfee",
  "fcagate.exe": "McAfee",
  "360EntClient.exe": "天擎EDR Agent",
  "QaxEntClient.exe": "天擎EDR Agent",
  "QAXTray.exe": "天擎EDR Agent",
  "edr_sec_plan.exe": "深信服EDR Agent",
  "edr_monitor.exe": "深信服EDR Agent",
  "edr_agent.exe": "深信服EDR Agent",
  "ESCCControl.exe": "启明星辰天珣EDR Agent",
  "ESCC.exe": "启明星辰天珣EDR Agent",
  "ESAV.exe": "启明星辰天珣EDR Agent",
  "ESCCIndex.exe": "启明星辰天珣EDR Agent",
  "AliYunDun.exe": "阿里云云盾",
  "wdswfsafe.exe": "360杀毒-网盾",
  "TopsecMain.exe": "天融信终端防御",
  "TopsecTray.exe": "天融信终端防御",
  "YDLive.exe": "腾讯云-云镜",
  "YDService.exe": "腾讯云-云镜",
  "TitanAgent.exe": "天眼云镜",
  "TitanMonitor.exe": "天眼云镜",
  "gse_win_daemon.exe": "蓝鲸Agent",
  "gse_win_agent.exe": "蓝鲸Agent",
  "QHActiveDefense.exe": "360 Total Security (360国际版)",
  "QHWatchdog.exe": "360 Total Security (360国际版)",
  "QHSafeTray.exe": "360 Total Security (360国际版)",
  "QHSafeMain.exe": "360 Total Security (360国际版)",
  "JingYunMonSvr.exe": "景云防病毒",
  "JingyunSdMainSvr.exe": "景云防病毒",
  "JingyunSdSvr.exe": "景云防病毒",
  "JingyunSdTray.exe": "景云防病毒",
};

const LEGACY_SIGNATURES_INTERNAL: SoftwareSignature[] = [];
Object.entries(LEGACY_AV_LIST).forEach(([rawProc, rawName]) => {
  const proc = rawProc.trim();
  if (!proc) {
    return;
  }
  const key = lower(proc);
  if (PROCESS_LOOKUP.has(key)) {
    return;
  }
  const displayName = (rawName || proc).trim() || proc;
  const signature: SoftwareSignature = {
    id: `legacy-${key}`,
    category: "杀软/安全防护",
    displayName,
    processes: [proc],
    description: "来自 avList 指纹库",
    source: "legacy",
  };
  PROCESS_LOOKUP.set(key, signature);
  LEGACY_SIGNATURES_INTERNAL.push(signature);
});

export const LEGACY_SIGNATURES = LEGACY_SIGNATURES_INTERNAL;
export const CURATED_SIGNATURE_COUNT = SOFTWARE_SIGNATURES.length;
export const LEGACY_SIGNATURE_COUNT = LEGACY_SIGNATURES.length;
export const TOTAL_SIGNATURE_COUNT =
  CURATED_SIGNATURE_COUNT + LEGACY_SIGNATURE_COUNT;

export interface PrivEscEntry {
  id: string;
  kbList: string[];
  vector: string;
  platforms: string;
}

export const PRIV_ESC_LIST: PrivEscEntry[] = [
  {
    id: "MS17-017",
    kbList: ["KB4013081"],
    vector: "GDIPaletteObjectsLocalPrivilegeEscalation",
    platforms: "windows7/8",
  },
  {
    id: "MS17-010",
    kbList: ["KB4013389"],
    vector: "WindowsKernelModeDrivers",
    platforms: "windows7/2008/2003/XP",
  },
  {
    id: "MS16-135",
    kbList: ["KB3199135"],
    vector: "WindowsKernelModeDrivers",
    platforms: "2016",
  },
  {
    id: "MS16-111",
    kbList: ["KB3186973"],
    vector: "kernelapi",
    platforms: "Windows1010586(32/64)/8.1",
  },
  {
    id: "MS16-098",
    kbList: ["KB3178466"],
    vector: "KernelDriver",
    platforms: "Win8.1",
  },
  {
    id: "MS16-075",
    kbList: ["KB3164038"],
    vector: "HotPotato",
    platforms: "2003/2008/7/8/2012",
  },
  {
    id: "MS16-034",
    kbList: ["KB3143145"],
    vector: "KernelDriver",
    platforms: "2008/7/8/10/2012",
  },
  {
    id: "MS16-032",
    kbList: ["KB3143141"],
    vector: "SecondaryLogonHandle",
    platforms: "2008/7/8/10/2012",
  },
  {
    id: "MS16-016",
    kbList: ["KB3136041"],
    vector: "WebDAV",
    platforms: "2008/Vista/7",
  },
  {
    id: "MS16-014",
    kbList: ["K3134228"],
    vector: "remotecodeexecution",
    platforms: "2008/Vista/7",
  },
  {
    id: "MS15-097",
    kbList: ["KB3089656"],
    vector: "remotecodeexecution",
    platforms: "win8.1/2012",
  },
  {
    id: "MS15-076",
    kbList: ["KB3067505"],
    vector: "RPC",
    platforms: "2003/2008/7/8/2012",
  },
  {
    id: "MS15-077",
    kbList: ["KB3077657"],
    vector: "ATM",
    platforms: "XP/Vista/Win7/Win8/2000/2003/2008/2012",
  },
  {
    id: "MS15-061",
    kbList: ["KB3057839"],
    vector: "KernelDriver",
    platforms: "2003/2008/7/8/2012",
  },
  {
    id: "MS15-051",
    kbList: ["KB3057191"],
    vector: "WindowsKernelModeDrivers",
    platforms: "2003/2008/7/8/2012",
  },
  {
    id: "MS15-015",
    kbList: ["KB3031432"],
    vector: "KernelDriver",
    platforms: "Win7/8/8.1/2012/RT/2012R2/2008R2",
  },
  {
    id: "MS15-010",
    kbList: ["KB3036220"],
    vector: "KernelDriver",
    platforms: "2003/2008/7/8",
  },
  {
    id: "MS15-001",
    kbList: ["KB3023266"],
    vector: "KernelDriver",
    platforms: "2008/2012/7/8",
  },
  {
    id: "MS14-070",
    kbList: ["KB2989935"],
    vector: "KernelDriver",
    platforms: "2003",
  },
  {
    id: "MS14-068",
    kbList: ["KB3011780"],
    vector: "DomainPrivilegeEscalation",
    platforms: "2003/2008/2012/7/8",
  },
  {
    id: "MS14-058",
    kbList: ["KB3000061"],
    vector: "Win32k.sys",
    platforms: "2003/2008/2012/7/8",
  },
  {
    id: "MS14-066",
    kbList: ["KB2992611"],
    vector: "WindowsSchannelAllowingremotecodeexecution",
    platforms:
      "VistaSP2/7SP1/8/Windows8.1/2003SP2/2008SP2/2008R2SP1/2012/2012R2/WindowsRT/WindowsRT8.1",
  },
  {
    id: "MS14-040",
    kbList: ["KB2975684"],
    vector: "AFDDriver",
    platforms: "2003/2008/2012/7/8",
  },
  {
    id: "MS14-002",
    kbList: ["KB2914368"],
    vector: "NDProxy",
    platforms: "2003/XP",
  },
  {
    id: "MS13-053",
    kbList: ["KB2850851"],
    vector: "win32k.sys",
    platforms: "XP/Vista/2003/2008/win7",
  },
  {
    id: "MS13-046",
    kbList: ["KB2840221"],
    vector: "dxgkrnl.sys",
    platforms: "Vista/2003/2008/2012/7",
  },
  {
    id: "MS13-005",
    kbList: ["KB2778930"],
    vector: "KernelModeDriver",
    platforms: "2003/2008/2012/win7/8",
  },
  {
    id: "MS12-042",
    kbList: ["KB2972621"],
    vector: "ServiceBus",
    platforms: "2008/2012/win7",
  },
  {
    id: "MS12-020",
    kbList: ["KB2671387"],
    vector: "RDP",
    platforms: "2003/2008/7/XP",
  },
  {
    id: "MS11-080",
    kbList: ["KB2592799"],
    vector: "AFD.sys",
    platforms: "2003/XP",
  },
  {
    id: "MS11-062",
    kbList: ["KB2566454"],
    vector: "NDISTAPI",
    platforms: "2003/XP",
  },
  {
    id: "MS11-046",
    kbList: ["KB2503665"],
    vector: "AFD.sys",
    platforms: "2003/2008/7/XP",
  },
  {
    id: "MS11-011",
    kbList: ["KB2393802"],
    vector: "kernelDriver",
    platforms: "2003/2008/7/XP/Vista",
  },
  {
    id: "MS10-092",
    kbList: ["KB2305420"],
    vector: "TaskScheduler",
    platforms: "2008/7",
  },
  {
    id: "MS10-059",
    kbList: ["KB982799"],
    vector: "ACL-Churraskito",
    platforms: "2008/7/Vista",
  },
  {
    id: "MS10-048",
    kbList: ["KB2160329"],
    vector: "win32k.sys",
    platforms: "XPSP2&SP3/2003SP2/VistaSP1&SP2/2008Gold&SP2&R2/Win7",
  },
  {
    id: "MS10-015",
    kbList: ["KB977165"],
    vector: "KiTrap0D",
    platforms: "2003/2008/7/XP",
  },
  {
    id: "MS10-012",
    kbList: ["KB971468"],
    vector: "SMBClientTrans2stackoverflow",
    platforms: "Windows7/2008R2",
  },
  {
    id: "MS09-050",
    kbList: ["KB975517"],
    vector: "RemoteCodeExecution",
    platforms: "2008/Vista",
  },
  {
    id: "MS09-020",
    kbList: ["KB970483"],
    vector: "IIS6.0",
    platforms: "IIS5.1and6.0",
  },
  {
    id: "MS09-012",
    kbList: ["KB959454"],
    vector: "Chimichurri",
    platforms: "Vista/win7/2008/Vista",
  },
  {
    id: "MS08-068",
    kbList: ["KB957097"],
    vector: "RemoteCodeExecution",
    platforms: "2000/XP",
  },
  {
    id: "MS08-067",
    kbList: ["KB958644"],
    vector: "RemoteCodeExecution",
    platforms: "Windows2000/XP/Server2003/Vista/Server2008",
  },
  {
    id: "MS08-066",
    kbList: ["KB956803"],
    vector: "AFD.sys",
    platforms: "Windows2000/XP/Server2003",
  },
  {
    id: "MS08-025",
    kbList: ["KB941693"],
    vector: "Win32.sys",
    platforms: "XP/2003/2008/Vista",
  },
  {
    id: "MS06-040",
    kbList: ["KB921883"],
    vector: "RemoteCodeExecution",
    platforms: "2003/xp/2000",
  },
  {
    id: "MS05-039",
    kbList: ["KB899588"],
    vector: "PnPService",
    platforms: "Win9X/ME/NT/2000/XP/2003",
  },
  {
    id: "MS03-026",
    kbList: ["KB823980"],
    vector: "BufferOverrunInRPCInterface",
    platforms: "NT/2000/XP/2003",
  },
  {
    id: "CVE-2020-1034",
    kbList: [
      "KB4577015",
      "KB4574727",
      "KB4571756",
      "KB4570333",
      "KB4577038",
      "KB4577048",
      "KB4577049",
      "KB4577066",
      "KB4577071",
      "KB4577032",
      "KB4577041",
    ],
    vector: "ntoskrnl.exe",
    platforms: "2019/2016/2012/2004/1903/1909/Win10、8.1",
  },
  {
    id: "CVE-2020-1052",
    kbList: [
      "KB4571756",
      "KB4577041",
      "KB4577015",
      "KB4577064",
      "KB4577070",
      "KB4574727",
      "KB4570333",
      "KB4577051",
      "KB4577053",
      "KB4577049",
      "KB4577066",
      "KB4577071",
      "KB4577038",
      "KB4577048",
      "KB4577032",
    ],
    vector: "ssdpsrv.dl",
    platforms: "1909/2004/2008/2012/2016/2019/Win10、7、8.1",
  },
  {
    id: "CVE-2022-21882",
    kbList: ["KB5009566", "KB5009543", "KB5009558"],
    vector: "Win32k Window Object Elevation",
    platforms: "Windows 11 21H2 / Windows 10 21H2 / Server 2022 (Jan 2022)",
  },
  {
    id: "CVE-2022-37969",
    kbList: ["KB5017328", "KB5017308", "KB5017315"],
    vector: "CLFS Driver Elevation",
    platforms: "Windows 11 21H2 / Windows 10 21H2 / Server 2022 (Sep 2022)",
  },
  {
    id: "CVE-2023-23376",
    kbList: ["KB5023698", "KB5023696", "KB5023706"],
    vector: "Win32k Type Confusion",
    platforms: "Windows 11 22H2 / Windows 10 22H2 / Server 2022 (Mar 2023)",
  },
  {
    id: "CVE-2023-28252",
    kbList: ["KB5025239", "KB5025224", "KB5025244"],
    vector: "CLFS Zero-Day Elevation",
    platforms: "Windows 11 22H2 / Windows 10 22H2 / Server 2022 (Apr 2023)",
  },
  {
    id: "CVE-2023-29336",
    kbList: ["KB5026372", "KB5026361", "KB5026363"],
    vector: "Win32k Lock Screen Bypass",
    platforms: "Windows 11 22H2 / Windows 10 22H2 / Server 2022 (May 2023)",
  },
  {
    id: "CVE-2024-21338",
    kbList: ["KB5034765", "KB5034763", "KB5034770"],
    vector: "CLFS Policy Elevation",
    platforms: "Windows 11 23H2 / Windows 10 22H2 / Server 2022 (Feb 2024)",
  },
];
